### ISSUE TITLE
AAC Playback - Recording

### ISSUE THREAD

**Issue by snibles** [sfuhrm/radiorecorder#4] opened 2023-01-09 19:06 UTC
Hello!

This application is awesome. You should provide some way so we can donate to this project.
I just wish to know if there is technical challenges to allow playback for AAC streams, or if this is not present due to some kind of license problem.

Would love to hear what's the status of AAC streams playback and recording, since my favorite stations are currently streaming on AAC.  :)

Thanks!

**Comment by sfuhrm** [comment] 2023-02-04 12:58
AAC recording should work fine at the moment.

AAC playback is lacking a good AAC Java library to decode  at the moment.

There are some AAC decoding libraries, but they are AFAIK not yet production-ready:
* The [JAAD](http://jaadec.sourceforge.net/) decoder seems to be the best pick, but with current streams it is not decoding. Code is no longer maintained. I have debugged a bit of the code and it looks like there decoder is hanging when it tries to find the beginning of a AAC frame. Either it is a simple bug (?) or the whole concept is broken.
* An updated (?) fork of JAAD is [JAADec](https://github.com/DV8FromTheWorld/JAADec), I think I reproduced the bug mentioned above also there.
* There are some other solutions needing native libraries or applications, this would break the platform independence of radiorecorder.

**Comment by snibles** [comment] 2023-02-08 20:57
> AAC recording should work fine at the moment.
> 
> AAC playback is lacking a good AAC Java library to decode at the moment.
> 
> There are some AAC decoding libraries, but they are AFAIK not yet production-ready:
> 
> * The [JAAD](http://jaadec.sourceforge.net/) decoder seems to be the best pick, but with current streams it is not decoding. Code is no longer maintained. I have debugged a bit of the code and it looks like there decoder is hanging when it tries to find the beginning of a AAC frame. Either it is a simple bug (?) or the whole concept is broken.
> * An updated (?) fork of JAAD is [JAADec](https://github.com/DV8FromTheWorld/JAADec), I think I reproduced the bug mentioned above also there.
> * There are some other solutions needing native libraries or applications, this would break the platform independence of radiorecorder.

That's good to know.
Thanks for the feedback @sfuhrm.
Let hope that a good and open source decoder arises!

**Comment by sfuhrm** [comment] 2024-01-28 12:13
Hi @snibles 

I had another look into the AAC decoder problem today and found out that the decoder is failing when it mis-interprets a MP3 stream as a AAC stream. I have replaced a certain audio format recognition and now we're not running into this bug anymore.

There's now also a test for all the supported sound formats.

I'll release the new version first as a alpha release in case you want to play around.

Best wishes,
Stephan

**Comment by sfuhrm** [comment] 2024-01-28 12:26
Please check v1.10.0 (pre-release)

**Comment by sfuhrm** [comment] 2024-01-28 12:36
Test stream replay works.
Real station stream does not work.

**Comment by sfuhrm** [comment] 2024-01-28 14:08
Rework in 1.10.1 works for now in testing.

**Comment by sfuhrm** [comment] 2024-02-11 12:06
Current situation is like this:
The AAC plugin works, but whenever it gets presented other data than AAC it easily ends in an endless loop.
My preference here is to include a manipulated version of the JAR that does not register as a plugin, but is used explicitly when radiorecorder sees an AAC stream.

**Comment by sfuhrm** [comment] 2024-11-09 15:42
I have reworked the code a bit to make the AAC plugin to *not* auto-detect streams.
This is now in release version https://github.com/sfuhrm/radiorecorder/releases/tag/v1.11.0
I'm closing the ticket. In case of problems, please open new issues.

**Closed by sfuhrm** 2024-11-09 15:42 UTC
